### ISSUE TITLE
YOU THIS SHIT-CODER

### ISSUE THREAD

**Issue by ghost** [veme312/AntiGM#2]
`}elseif($dmg->isFlying() != null){
 }`

WHAT THIS?

**Comment by veme312** [comment]
https://github.com/TuranicTeam/Turanic/blob/9c426c443672f3faf1f096495a5a5b142ebd6cd4/src/pocketmine/event/player/PlayerToggleFlightEvent.php#L47

**Comment by ghost** [comment]
Давай на русском. Я имею ввиду, нахрена это проверка нужна?

**Comment by veme312** [comment]
> нахрена это проверка нужна?

Эта проверка на нахождение игрока во флае.

**Comment by ghost** [comment]
В ней ничего не происходит
